title: mit6.284
description: Distribution Systems Notes and Stuff
author: "Sangarshanan"

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

# Minima: custom header links
header_pages:
  - _posts/glossary.md

theme: minima

include:
    - _pages
