title: mit6.284
description: Distributed Systems Notes and Stuff
author: "Sangarshanan"

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sangarshanan
    github:  sangarshanan

# Minima: custom header links
header_pages:
  - glossary.md
  - about.md

theme: minima
